routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Auth\LoginController@index')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');

Route::middleware(['auth'])->group(function () {
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');

	Route::prefix('api')->namespace('api')->name('api.')->group(function() {
		Route::prefix('api')->namespace('api')->name('api.')->group(function() {

		});
	});

	Route::prefix('profile')->namespace('profile')->name('profile.')->group(function() {
		Route::resource('general', 'GeneralController');
		Route::resource('emergency', 'EmergencyController');
		Route::resource('password', 'PasswordController');
	});
	Route::resource('profile', 'ProfileController');

	Route::resource('student', 'StudentController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('student')->namespace('student')->name('student.')->group(function() {
		Route::prefix('profile')->namespace('profile')->name('profile.')->group(function() {
			Route::resource('general', 'GeneralController');
			Route::resource('growth', 'GrowthController');
			Route::resource('emergency', 'EmergencyController');
			Route::resource('address', 'AddressController');
			Route::resource('subject', 'SubjectController');
			Route::resource('password', 'PasswordController');
		});
	});

	Route::resource('lesson', 'LessonController',[
		'only' => ['index']
	]);
	Route::prefix('lesson')->name('lesson.')->group(function() {
		Route::get('getsubject', 'LessonController@getSubject')->name('getsubject');
		Route::get('getclasses', 'LessonController@getClasses')->name('getclasses');
		Route::get('getroom', 'LessonController@getRoom')->name('getroom');
		Route::get('download', 'LessonController@download')->name('download');
	});

	Route::resource('checkanswer', 'CheckAnswerController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('checkanswer')->name('checkanswer.')->group(function() {
		Route::get('detail', 'CheckAnswerController@detail')->name('detail');
		Route::get('check', 'CheckAnswerController@check')->name('check');
		Route::get('getanswer', 'CheckAnswerController@getAnswer')->name('getanswer');
	});

	Route::resource('checkexercise', 'CheckExerciseController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('checkexercise')->name('checkexercise.')->group(function() {
		Route::get('approve', 'CheckExerciseController@approve')->name('approve');
	});
});

app/Models/Term.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Term extends Model // implements AuditableContract
{
    // use SoftDeletes;

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    // protected static function boot()
    // {
    //     parent::boot();
    //     static::addGlobalScope(new ProjectScope());
    // }

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'terms';

    /**
     * override Eloquent's default a primary key column named id.
     * @var string
     */
    // protected $primaryKey = 'id';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    // public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    // public $timestamps = false;
    // const CREATED_AT = null;
    // const UPDATED_AT = null;

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    // protected $appends = [
    //     //
    // ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     //
    // ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    // protected $dates = [
    //     //
    // ];

    /**
     * The event map for the model.
     *
     * @var array
     */
    // protected $dispatchesEvents = [
    //     //
    // ];

    /**
     * The attributes that should be encrypted on save.
     *
     * @var array
     */
    // protected $encrypted = [
    //     //
    // ];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'school_id',
        'year',
        'term',
        'startDate',
        'endDate',
        'lastTerm',
        'behavior',
        'active',
        'masterplan_active',
        'comment',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be hashed on save.
     *
     * @var array
     */
    // protected $hashed = [
    //     //
    // ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    // protected $hidden = [
    //     //
    // ];

    /**
     * Attribute Getters
     */
    // public function getExampleAttribute()
    // {
    //     return $this->attributes['example'] / 2 ;
    // }
    public function getTermnumberAttribute()
    {
        $name = "";
        if($this->term == 'term_1') {
            $name = '1';
        } else if($this->term == 'term_2') {
            $name = '2';
        } else if($this->term == 'term_3') {
            $name = '3';
        }
        return $name;
    }

    public function getTermthaiAttribute()
    {
        return $this->year + 543;
    }

    public function getFullnameAttribute()
    {
        $name = "ปี " . $this->year. " เทอม " . $this->termnumber;
        return $name;
    }

    /**
     * Attribute Setters
     */
    // public function setExampleAttribute($newExample)
    // {
    //     $this->attributes['example'] = $newExample * 2;
    // }

    /**
     * Relationships
     */
    // public function school()
    // {
    //     return $this->hasOne(school::class, 'id', 'school_id');
    // }

    /**
     * Scopes
     */
    // public function scopeExample(Builder $query, $q) {
    //     return $query->where('example', '=', $q);
    // }
}

app/Http/Controllers/CheckAnswerController.php
<?php

namespace App\Http\Controllers;

use Alert;
use App\Models\Advisor;
use App\Models\Classes;
use App\Models\School;
use App\Models\Sheetset;
use App\Models\SheetQuestion;
use App\Models\SubjectLesson;
use App\Models\Subject;
use App\Models\Term;
use Illuminate\Http\Request;
use PDF;

class CheckAnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter_term = $request->input('filter_term')==""?null:$request->input('filter_term');
        $filter_subject = $request->input('filter_subject')==""?null:$request->input('filter_subject');
        $filter_classes = $request->input('filter_classes')==""?null:$request->input('filter_classes');
        $payloads = array();

        $terms = Term::where('school_id', Auth()->user()->school_id)
            ->orderBy('year', 'desc')
            ->orderBy('term', 'asc')
            ->get();
        
        if ($filter_term != null && $filter_subject != null && $filter_classes != null) {
            $term = Term::where('id', $request->input('filter_term'))
                ->firstorfail();

            $payloads = SubjectLesson::where([
                'subject_lesson.subject_id' => $filter_subject,
                'subject_lesson.classes_id' => $filter_classes,
                'subject_lesson.year'       => $term->year,
            ])->select('subject_lesson.*','subject_lesson_school_order.sort AS school_sort')
            ->leftJoin('subject_lesson_school_order', 'subject_lesson_school_order.lesson_id', '=', 'subject_lesson.id')
            ->where('subject_lesson_school_order.sort', '>', '0')
            ->where('subject_lesson_school_order.school_id', Auth()->user()->school_id)
            ->where('subject_lesson_school_order.term_id', $filter_term)
            ->orderBy('level_id')->orderBy('school_sort')
            ->get();
        }

        return view('checkanswer.index', compact([
            'terms',
            'filter_term',
            'filter_subject',
            'filter_classes',
            'payloads'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function detail(Request $request)
    {
        $payload = Sheetset::where('id', $request->input('sheetset'))
            ->first();
        
        return view('checkanswer.detail', compact(
            'payload'
        ));
    }
    public function check(Request $request)
    {
        $question 	= SheetQuestion::find($request->input('id'));
		$decode 	= json_decode($question->posts);
		$index 		= $request->input('index');
        $result 	= "";

        //ใช้สำหรับนับจำนวนของ foreach ว่าตอนนี้วนไปแล้วกี่รอบโดยให้ค่าตั้งต้นอยู่ที่ 1ไม่ใช่ 0
		if (!empty($decode)) {
			foreach ($decode as $indexDecode => $valueDecode) {
				++$indexDecode;
				if ( $index == $indexDecode) {
					switch ($valueDecode->type) {
						case 'choice':
							if (! empty($valueDecode->correct)) {
								$correct 	= explode('|', $valueDecode->correct);
								$result 	= in_array($request->input('choose'), $correct) ? true : false;
							} else {
								$request = false;
							}
						break;
							
						case 'choiceimage':
							if (! empty($valueDecode->correct)) {
								$correct 	= explode('|', $valueDecode->correct);
								$result 	= in_array($request->input('choose'), $correct) ? true : false;
							} else {
								$result = false;
							}
						break;
							
						case 'write':
							if (! empty($valueDecode->answer)) {
								if (is_numeric($request->input('choose'))) {
									$choose = $request->input('choose');
								} else {
									$choose = $request->input('choose');
								}
								// $correct 	= explode(',', $valueDecode->answer);
								$result 	= $choose==$valueDecode->answer? true : false;
							} else {
								$result = false;
							}
						break;
							
						case 'choicewrite':
							if (! empty($valueDecode->answerWrite) && ! empty($valueDecode->correctChoice)) {
								// $correctWrite 	= explode(',', $valueDecode->answerWrite);
								$correctChoice 	= explode('|', $valueDecode->correctChoice);
								if (is_numeric($request->input('chooseWrited'))) {
									$choose = $request->input('chooseWrited');
								} else {
									$choose = $request->input('chooseWrited');
								}

								$result = ( $choose==$valueDecode->answerWrite) && (in_array($request->input('chooseChoice'), $correctChoice) ? true : false);
							}
						break;
					}
				}
			}
		}
		
		return response()->json(['status' => true, 'result' => $result ]);
    }

    public function getAnswer(Request $request)
	{	
        $question = SheetQuestion::where('id', $request->input('question'))
            ->first();

		if ($request->input('type')==1) {
			return response()->json([
				'html' => $question->explanation ? $question->explanation . '<br><a class="btn btn-danger removeAnswer">ปิดเฉลย</a>' : null
			]);
		} else {
			$explanation = "";
			$decode = json_decode($question->posts);
			foreach ($decode as $indexDecode => $valueDecode) {
				if ($indexDecode==($request->input('index')-1)) {
					$explanation = empty($valueDecode->explanation) ? "" : $valueDecode->explanation;
					$explanation_type = empty($valueDecode->explanation_type) ? "" : $valueDecode->explanation_type;
				}
			}

			if ($explanation_type==2) {
				$explanation = "<img src='".asset('question/'.$explanation)."' width='300' />";
			} elseif($explanation_type==3) {
				$explanation = "<iframe width='400' height='300' src='https://www.youtube.com/embed/".$explanation."'></iframe>";
			}

			return response()->json([
				'html' => $explanation.'<br><a class="removeAnswerPart">ปิดเฉลย</a>'
			]);
		}
	}
}

resources/views/checkanswer/index.blade.php
@extends('layouts.master')

@section('css')
@endsection

@section('title')
    รายการตรวจคำตอบ
@endsection

@section('breadcrumd')
@endsection

@section('actions')
@endsection

@section('content')
<div class="card card-custom gutter-b" id="kt_card_1">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">ค้นหาข้อมูล</h3>
        </div>
        <div class="card-toolbar">
            <a href="#" class="btn btn-icon btn-sm btn-hover-light-primary mr-1" data-card-tool="toggle" data-toggle="tooltip" data-placement="top" title="Search">
                <i class="ki ki-arrow-down icon-nm"></i>
            </a>
        </div>
    </div>
    <div class="card-body p-0">
        <form class="form">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-lg-4">
                        <label>ปี-เทอมการศึกษา:</label>
                        <div class="input-group">
                            <select name="filter_term" id="filter_term" class="form-control selectpicker" data-live-search="true">
                                    <option value="">--- เลือกปี เทอมการศึกษา ---</option>
                                @foreach($terms as $term)
                                    <option value="{{$term->id}}" {{$term->id==$filter_term?'selected':''}}>{{$term->fullname}}</option>
                                @endforeach
                            </select>
                        </div>
                        <span class="form-text text-muted"></span>
                    </div>
                    <div class="col-lg-4">
                        <label>วิชาเรียน:</label>
                        <div class="input-group">
                            <select name="filter_subject" id="filter_subject" class="form-control selectpicker" data-live-search="true">
                                    <option value="">--- เลือกวิชาเรียน ---</option>
                            </select>
                        </div>
                        <span class="form-text text-muted"></span>
                    </div>
                    <div class="col-lg-4">
                        <label>ชั้นเรียน:</label>
                        <div class="input-group">
                            <select name="filter_classes" id="filter_classes" class="form-control selectpicker" data-live-search="true">
                                    <option value="">--- เลือกชั้นเรียน ---</option>
                            </select>
                        </div>
                        <span class="form-text text-muted"></span>
                    </div>
                </div>
                <div class="text-right">
                    <button class="btn btn-light-primary font-weight-bold mr-2"><i class="fa fa-search"></i> ค้นหา</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    @foreach($payloads as $payload)
        <div class="col-xl-6">
            <!--begin::Card-->
            <div class="card card-custom gutter-b card-stretch">
                <!--begin::Body-->
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <!--begin::Info-->
                        <div class="d-flex flex-column mr-auto">
                            <div class="d-flex mb-5 align-items-cente">
                                <span class="d-block font-weight-bold mr-5">บทเรียน</span>
                                <div class="d-flex flex-row-fluid align-items-center">
                                    <span class="ml-3 font-weight-bolder">{{ $payload->code }}</span>
                                </div>
                            </div>
                            <div class="d-flex mb-5 align-items-cente">
                                <span class="d-block font-weight-bold mr-5">ชื่อบทเรียน</span>
                                <div class="d-flex flex-row-fluid align-items-center">
                                    <span class="ml-3 font-weight-bolder">{{ $payload->name }}</span>
                                </div>
                            </div>
                            <div class="d-flex mb-5 align-items-cente">
                                <span class="d-block font-weight-bold mr-5">หมวดหมู่วิชา/หลักสูตร</span>
                                <div class="d-flex flex-row-fluid align-items-center">
                                    <span class="ml-3 font-weight-bolder">{{ $payload->subject ? $payload->subject->name : '' }}</span>
                                </div>
                            </div>
                            <div class="d-flex mb-5 align-items-cente">
                                <span class="d-block font-weight-bold mr-5">ตำแหน่ง</span>
                                <div class="d-flex flex-row-fluid align-items-center">
                                    <span class="ml-3 font-weight-bolder">{{ $payload->sort }}</span>
                                </div>
                            </div>
                        </div>
                        <!--end::Info-->
                    </div>
                    <!--end::Info-->
                    
                    <div class="separator separator-solid my-7"></div>

                    <div class="row">
                        <div class="col-lg-12 col-xs-12">
                            <div class="accordion accordion-solid accordion-toggle-plus" id="accordionExample3">
                                @foreach($payload->sheetsets() as $sheetset)
                                    @php
                                        $lablesson = $payload->lablesson($sheetset->id);
                                        if ($lablesson) {
                                            if ($lablesson->lab->level_id == "1") {
                                                $background = "bg-light-success";
                                            } else if ($lablesson->lab->level_id == "2") {
                                                $background = "bg-light-dark";
                                            } else if ($lablesson->lab->level_id == "3") {
                                                $background = "bg-light-danger";
                                            } else {
                                                $background = "bg-light-warning";
                                            }
                                        } else {
                                            $background = "bg-light-warning";
                                        }
                                    @endphp
                                    @if($lablesson)
                                        <a href="{{ route('checkanswer.detail') }}?sheetset={{$sheetset->id}}" class="btn btn-light-success btn-block text-dark font-weight-bold mr-2">
                                            {{$sheetset->code}} {{$lablesson ? $lablesson->name : ''}}
                                        </a>
                                    @endif
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
                <!--end::Body-->
            </div>
            <!--end:: Card-->
        </div>
    @endforeach
</div>
@endsection

@section('script')
<script src="{{asset('js/selected.js')}}"></script>
<script>
    // This card is lazy initialized using data-card="true" attribute. You can access to the card object as shown below and override its behavior
    var card = new KTCard('kt_card_1');

    // Toggle event handlers
    card.on('beforeCollapse', function (card) {
        setTimeout(function () {
            // toastr.info('Before collapse event fired!');
        }, 100);
    });

    card.on('afterCollapse', function (card) {
        setTimeout(function () {
            // toastr.warning('Before collapse event fired!');
        }, 2000);
    });

    card.on('beforeExpand', function (card) {
        setTimeout(function () {
            // toastr.info('Before expand event fired!');
        }, 100);
    });

    card.on('afterExpand', function (card) {
        setTimeout(function () {
            // toastr.warning('After expand event fired!');
        }, 2000);
    });

    $(function(){
        $("#filter_term").trigger("change");
    })

    $(document).on('change', '#filter_term', function(){    // 2nd (B)
        $.ajax({
            type:"get",
            url: "{{ route('lesson.getsubject') }}",
            datatype: "Json",
            async: false,
            data: {
                filter_subject: "{{$filter_subject}}",
                term: $("#filter_term").val()
            }, success(response) {
                if (response.row > 0) {
                    html = "<option value=''>---เลือกวิชาเรียน---</option>";
                    for(var i = 0; i < response.row; i++) {
                        if (response.filter_subject==response.subject[i].subject_id) {
                            html += "<option value='"+response.subject[i].subject_id+"' selected>"+response.subject[i].subject.name+"</option>";
                        } else {
                            html += "<option value='"+response.subject[i].subject_id+"'>"+response.subject[i].subject.name+"</option>";
                        }
                    }
                    $("#filter_subject").html(html);
                    $("#filter_subject").selectpicker('refresh');
                }
            }
        })

        $.ajax({
            type:"get",
            url: "{{ route('lesson.getclasses') }}",
            datatype: "Json",
            async: false,
            data: {
                filter_classes: "{{$filter_classes}}",
                term: $("#filter_term").val()
            }, success(response) {
                console.log(response);
                if (response.row > 0) {
                    html = "<option value=''>---เลือกชั้นเรียน---</option>";
                    for(var i = 0; i < response.row; i++) {
                        if (response.filter_classes==response.classes[i].classes_id) {
                            html += "<option value='"+response.classes[i].classes_id+"' selected>"+response.classes[i].classes.name_th+"</option>";
                        } else {
                            html += "<option value='"+response.classes[i].classes_id+"'>"+response.classes[i].classes.name_th+"</option>";
                        }
                    }
                    $("#filter_classes").html(html);
                    $("#filter_classes").selectpicker('refresh');
                }
            }
        })
    });
</script>
@endsection