routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Auth\LoginController@index')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');

Route::middleware(['auth'])->group(function () {
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');

	Route::prefix('api')->namespace('api')->name('api.')->group(function() {
		Route::prefix('api')->namespace('api')->name('api.')->group(function() {

		});
	});

	Route::prefix('profile')->namespace('profile')->name('profile.')->group(function() {
		Route::resource('general', 'GeneralController');
		Route::resource('emergency', 'EmergencyController');
		Route::resource('password', 'PasswordController');
	});
	Route::resource('profile', 'ProfileController');

	Route::resource('student', 'StudentController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('student')->namespace('student')->name('student.')->group(function() {
		Route::prefix('profile')->namespace('profile')->name('profile.')->group(function() {
			Route::resource('general', 'GeneralController');
			Route::resource('growth', 'GrowthController');
			Route::resource('emergency', 'EmergencyController');
			Route::resource('address', 'AddressController');
			Route::resource('subject', 'SubjectController');
			Route::resource('password', 'PasswordController');
		});
	});

	Route::resource('lesson', 'LessonController',[
		'only' => ['index']
	]);
	Route::prefix('lesson')->name('lesson.')->group(function() {
		Route::get('getsubject', 'LessonController@getSubject')->name('getsubject');
		Route::get('getclasses', 'LessonController@getClasses')->name('getclasses');
		Route::get('getroom', 'LessonController@getRoom')->name('getroom');
		Route::get('download', 'LessonController@download')->name('download');
	});

	Route::resource('checkanswer', 'CheckAnswerController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('checkanswer')->name('checkanswer.')->group(function() {
		Route::get('detail', 'CheckAnswerController@detail')->name('detail');
		Route::get('check', 'CheckAnswerController@check')->name('check');
		Route::get('getanswer', 'CheckAnswerController@getAnswer')->name('getanswer');
	});

	Route::resource('checkexercise', 'CheckExerciseController', [
		'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
	]);
	Route::prefix('checkexercise')->name('checkexercise.')->group(function() {
		Route::get('approve', 'CheckExerciseController@approve')->name('approve');
	});
});

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Models\Teacher;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('profile.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Teacher $teacher)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        //
    }
}

app/Http/Controllers/profile/EmergencyController.php
<?php

namespace App\Http\Controllers\profile;

use Alert;
use App\Http\Requests\profile\EmergencyRequest;
use App\Http\Controllers\Controller;
use App\Models\Teacher;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;

class EmergencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('profile.emergency.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmergencyRequest $request)
    {
        $auth = Auth::user();
        $teacher = Teacher::find($auth->teacher->id);
        if ($teacher) {
            Teacher::where('id', $auth->teacher->id)->update([
                'emergency_name1' => $request->input('emergency_name1'),
                'emergency_name2' => $request->input('emergency_name2'),
                'emergency_name3' => $request->input('emergency_name3'),
                'emergency_relationship1' => $request->input('emergency_relationship1'),
                'emergency_relationship2' => $request->input('emergency_relationship2'),
                'emergency_relationship3' => $request->input('emergency_relationship3'),
            ]);

            Alert::html('บันทึกสำเร็จ', "ทำการอัพเดตข้อมูลติดต่อฉุกเฉินเรียบร้อยแล้ว", 'success');
            return redirect()->back();

        } else {
            Alert::html('ข้อมูลผิดพลาด', "ไม่สามารถอัพเดตข้อมูลข้อมูลติดต่อฉุกเฉินได้", 'error');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/profile/GeneralController.php
<?php

namespace App\Http\Controllers\profile;

use Alert;
use App\Http\Requests\profile\GeneralRequest;
use App\Http\Controllers\Controller;
use App\Models\Teacher;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;

class GeneralController extends Controller
{
    public $uploadPath = 'uploads/profiles/teachers';
    public $extension = array('jpg', 'jpeg', 'png');
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('profile.general.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GeneralRequest $request)
    {
        $auth = Auth::user();
        $teacher = Teacher::find($auth->teacher->id);
        if ($teacher) {
            $teacher->update([
                'firstname' => $request->input('firstname'),
                'lastname' => $request->input('lastname'),
                'firstname_en' => $request->input('firstname_en'),
                'lastname_en' => $request->input('lastname_en'),
                'birthday' => $request->input('birthday'),
                'high' => $request->input('high'),
                'weight' => $request->input('weight'),
                'nationality' => $request->input('nationality'),
                'race' => $request->input('race'),
                'phone' => $request->input('phone'),
                'email' => $request->input('email'),
                'status' => $request->input('status')
            ]);

            $user = User::find($auth->id);
            $user->update([
                'active' => $request->input('status')=="W"?0:1,
            ]);

            if ($request->hasFile('picture')) {
                $file = $request->file('picture');
                $fileName = md5(time()) . '.' . $file->getClientOriginalExtension();
                $destination_path = $this->uploadPath;
                if (in_array($file->getClientOriginalExtension(), $this->extension)) {
                    if ($file->move($destination_path, $fileName)) {
                        if (file_exists($auth->teacher->picture)){
                            @unlink($auth->teacher->picture);
                        }
                        Teacher::where('id', $auth->teacher->id)->update([
                            'picture' => $this->uploadPath . '/' . $fileName,
                        ]);
                    }
                }
            }

            Alert::html('บันทึกสำเร็จ', "ทำการอัพเดตข้อมูลส่วนตัวเรียบร้อยแล้ว", 'success');
            return redirect()->back();

        } else {
            Alert::html('ข้อมูลผิดพลาด', "ไม่สามารถอัพเดตข้อมูลส่วนตัวได้", 'error');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/profile/PasswordController.php
<?php

namespace App\Http\Controllers\profile;

use Alert;
use App\Http\Requests\profile\PasswordRequest;
use App\Http\Controllers\Controller;
use App\Models\Teacher;
use App\Models\User;
use Hash;
use Illuminate\Http\Request;

class PasswordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('profile.password.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PasswordRequest $request)
    {
        $auth = Auth()->user();
        if (Hash::check($request->input('password_current'), $auth->password)) {
            Teacher::where('id', $auth->teacher->id)->update([
                'password' => Hash::make($request->input('password'))
            ]);

            Alert::html('บันทึกสำเร็จ', "ทำการเปลี่ยนรหัสผ่านของคุณเรียบร้อยแล้ว", 'success');
        } else {
            Alert::html('ข้อมูลผิดพลาด', "รหัสผ่านของคุณไม่ถูก กรุณาใส่รหัสผ่านใหม่", 'error');
        }

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/student/profile/AddressController.php
<?php

namespace App\Http\Controllers\student\profile;

use Alert;
use App\Http\Requests\student\profile\AddressRequest;
use App\Http\Controllers\Controller;
use App\Models\Student;
use App\Models\User;
use Auth;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $payload = Student::where('id', $request->input('id'))
            ->where('SchoolId', Auth()->user()->school_id)
            ->firstorfail();

        return view('student.profile.address.index', compact(
            'payload'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payload = Student::where('id', $request->input('id'))
            ->where('SchoolId', Auth()->user()->school_id)
            ->firstorfail();
        if ($payload) {
            $payload->update([
                'StdAddress' => $request->input('address'),
                'StdTumbol' => $request->input('tumbol'),
                'StdAmphur' => $request->input('amphur'),
                'StdProvince' => $request->input('province'),
                'StdZipcode' => $request->input('zipcode'),
                'StdTel' => $request->input('phone'),
                'StdMobile' => $request->input('mobile'),
                'StdEmail' => $request->input('email'),
            ]);

            Alert::html('บันทึกสำเร็จ', "ทำการอัพเดตข้อมูลติดต่อฉุกเฉินเรียบร้อยแล้ว", 'success');
            return redirect()->back();
        } else {
            Alert::html('ข้อมูลผิดพลาด', "ไม่สามารถอัพเดตข้อมูลติดต่อฉุกเฉินได้", 'error');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/student/profile/password/index.blade.php
@extends('layouts.master')

@section('css')
@endsection

@section('title')
    แก้ไขข้อมูลการเข้าสู่ระบบของนักเรียน
@endsection

@section('breadcrumd')
    <a href="{{ route('student.index') }}" class="text-primary">รายการข้อมูลนักเรียน</a>
@endsection

@section('actions')
    <button type="button" class="btn btn-light-info mr-2" id="form-save"><i class="fa fa-save"></i> บันทึก</button>
@endsection

@section('content')
    <div class="d-flex flex-row">
        @include('layouts.student.profile.aside', ['payload', $payload])

        <!--begin::Body-->
        <div class="flex-row-fluid ml-lg-8">
            <div class="card card-custom card-stretch">
                <!--begin::Header-->
                <div class="card-header py-3">
                    <div class="card-title align-items-start flex-column">
                        <h3 class="card-label font-weight-bolder text-dark">แก้ไขข้อมูลการเข้าสู่ระบบของนักเรียน</h3>
                        <span class="text-muted font-weight-bold font-size-sm mt-1">อัพเดตข้อมูลการเข้าสู่ระบบของนักเรียน</span>
                    </div>
                    <div class="card-toolbar">
                        
                    </div>
                </div>
                <!--end::Header-->
        
                <!--begin::Form-->
                <form method="POST" action="{{ route('student.profile.password.store') }}" class="form" id="form-data">
                    @csrf
                    <input type="hidden" name="id" value="{{$payload->id}}" />
                    <!--begin::Body-->
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-alert">รหัสผ่านผัจจุบัน</label>
                            <div class="col-lg-9 col-xl-6">
                                <input type="password" class="form-control form-control-lg form-control-solid mb-2" name="password_current" value="" placeholder="รหัสผ่านผัจจุบัน">
                                <span class="text-sm font-weight-bold"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-alert">รหัสผ่านใหม่</label>
                            <div class="col-lg-9 col-xl-6">
                                <input type="password" class="form-control form-control-lg form-control-solid mb-2" name="password" value="" placeholder="รหัสผ่านใหม่?">
                                <span class="text-sm font-weight-bold"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-xl-3 col-lg-3 col-form-label text-alert">ยืนยันรหัสผ่าน</label>
                            <div class="col-lg-9 col-xl-6">
                                <input type="password" class="form-control form-control-lg form-control-solid mb-2" name="password_confirmation" value="" placeholder="ยืนยันรหัสผ่าน">
                                <span class="text-sm font-weight-bold"></span>
                            </div>
                        </div>

                        <hr />
                        <h4 class="card-title font-weight-bolder text-dark mb-2">ชื่อผู้ใช้ & รหัสผ่าน ปัจจุบัน</h4>
                        <div class="d-flex flex-wrap align-items-center justify-content-between w-100">
                            <!--begin::Info-->
                            <div class="d-flex flex-column align-items-cente py-2 w-75">
                                <!--begin::Title-->
                                <span class="text-dark-75 font-weight-bold font-size-lg mb-1">
                                    ชื่อผู้ใช้งาน
                                </span>
                                <!--end::Title-->
                            </div>
                            <!--end::Info-->
        
                            <!--begin::Label-->
                            <span class="label label-lg label-light-primary label-inline font-weight-bold py-4">{{ $payload->Username }}</span>
                            <!--end::Label-->
                        </div>
        
                        <div class="d-flex flex-wrap align-items-center justify-content-between w-100">
                            <!--begin::Info-->
                            <div class="d-flex flex-column align-items-cente py-2 w-75">
                                <!--begin::Title-->
                                <span class="text-dark-75 font-weight-bold text-hover-primary font-size-lg mb-1">
                                    รหัสผ่าน
                                </span>
                                <!--end::Title-->
                            </div>
                            <!--end::Info-->
        
                            <!--begin::Label-->
                            <span class="label label-lg label-light-primary label-inline font-weight-bold py-4">{{ $payload->Password }}</span>
                            <!--end::Label-->
                        </div>
                    </div>
                    <!--end::Body-->

                    
                </form>
                <!--end::Form-->
            </div>
        </div>
        <!--end::Body-->
    </div>
@endsection

@section('script')
<script>
    // Class definition
    var KTProfile = function () {
        // Elements
        var avatar;
        var offcanvas;

        // Private functions
        var _initAside = function () {
            // Mobile offcanvas for mobile mode
            offcanvas = new KTOffcanvas('kt_profile_aside', {
                overlay: true,
                baseClass: 'offcanvas-mobile',
                //closeBy: 'kt_user_profile_aside_close',
                toggleBy: 'kt_subheader_mobile_toggle'
            });
        }

        var _initForm = function() {
            avatar = new KTImageInput('kt_profile_avatar');
        }

        return {
            // public functions
            init: function() {
                _initAside();
                _initForm();
            }
        };
    }();

    jQuery(document).ready(function() {
        KTProfile.init();
    });
</script>
<script>
    $("#form-save").click(function(){
        $("#form-data").submit();
    });
</script>
@endsection